site_name: Iougurt Startup
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: default
    primary: indigo
    accent: light blue
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Início: index.md
    - Gestão e Evolução (Atual):
        - Backlog do Produto: backlog.md
        - Atividades da Sprint: atividades_sprint.md
        - Registro de Reuniões: registro_reunioes_sprint.md
        - Protótipo Mobile: prototipo.md
    - Legado (Disciplina Passada):
        - Requisitos Iniciais: requirements.md
        - Histórias de Usuário Base: us_stories.md
        - Planejamento MVP: mvp.md
        - Modelagem do Banco: banco.md
