site_name: Iougurt Startup
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: slate
    primary: red
    accent: orange
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Início: index.md
    - Requisitos: requirements.md
    - Histórias de usuário: us_stories.md
    - Planejamento MVP: mvp.md
